server:
  port: 8081

spring:
  application:
    name: DesignPatterns
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:design
    username: design
    password: design
  h2:
    console:
      enabled: true
      path: /myH2
  # 自动更新 DDL
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: debug

knife4j:
  enable: true
  openapi:
    title: 自学设计模式文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
